
steps:
- task: DeleteFiles@1
  inputs:
    sourceFolder: $(Build.SourcesDirectory)
    contents: '**'

- checkout: self
  clean: true

# Node.js Tool Installer
# Finds or downloads and caches the specified version spec of Node.js and adds it to the PATH.
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
    #checkLatest: false # Optional

- script: npm install -g cspell
  displayName: 'Install cspell npm'

- script: cspell docs/**/*.md
  displayName: 'Spell Check md files'

- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.7'
    architecture: 'x64'

- script: python -m pip install --upgrade pip
  displayName: 'Install/Upgrade tools'

- script: python -m pip install -r requirements.txt
  displayName: 'Install dependencies'

- task: CmdLine@1
  displayName: 'build'
  inputs:
    filename: mkdocs
    arguments: 'build -s -v '
