
steps:
- task: DeleteFiles@1
  inputs:
    sourceFolder: $(Build.SourcesDirectory)
    contents: '**'

- checkout: self
  clean: true

# Node.js Tool Installer
# Finds or downloads and caches the specified version spec of Node.js and adds it to the PATH.
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
    #checkLatest: false # Optional

- script: npm install -g cspell
  displayName: 'Install cspell npm'

- script: cspell docs/**/*.md
  displayName: 'Spell Check md files'

- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.7'
    architecture: 'x64'

- script: python -m pip install --upgrade pip
  displayName: 'Install/Upgrade pip'

- script: python -m pip install --upgrade -r requirements.txt
  displayName: 'Install/upgrade dependencies'

# For CI build don't use remote repos
- script: python DocBuild.py --clean --build --OutputDir docs --yml mkdocs_base.yml -o pr-gate.log
  displayName: 'Run Preprocess'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: Generated Yml File'
  inputs:
    PathtoPublish: 'mkdocs.yml'
    ArtifactName: 'mkdocs.yml'
  continueOnError: true
  condition: succeededOrFailed()

- task: CmdLine@1
  displayName: 'build'
  inputs:
    filename: mkdocs
    arguments: 'build -s -v '

- task: PublishBuildArtifacts@1
  displayName: 'Publish DocBuild Log'
  inputs:
    PathtoPublish: 'pr-gate.log'
    ArtifactName: 'DocBuild_Pr-Gate.log'
  continueOnError: true
  condition: failed()
