site_name: Project Mu
repo_url: https://github.com/microsoft/mu
copyright: Copyright (c) Microsoft.  All rights reserved
site_description: "Project Mu Documentation"
plugins:
    - search
    - macros

theme:
  name: 'material'
  custom_dir: 'theme'
  logo: 'img/mu.png'

nav:
  - Home: 'index.md'
  - What and Why:
    - Overview: 'WhatAndWhy/overview.md'
    - Dependencies and Layout: 'WhatAndWhy/layout.md'
    # - Componentization: 'WhatAndWhy/componentization.md'
  - Where:
    - Project Resources: 'Where/project_resources.md'
    - External Resources: 'Where/external_resources.md'
  - How:
    - Release Process: 'How/release_process.md'
    - Downstream Integration: 'How/downstream_integration.md'
    - Contributing: 'How/contributing.md'
    - Upstream Integration: 'How/upstream_integration.md'
  - Developer Docs:
    - Docs: "DeveloperDocs/developerdocs.md"
  - FAQ: 'faq.md'
  - License: 'license.md'

