site_name: Project Mu
repo_url: https://github.com/microsoft/mu
copyright: Copyright (c) Microsoft.  All rights reserved
theme: readthedocs
site_description: "Project Mu Documentation"
plugins:
    - search
    - macros

nav:
  - Home: 'index.md'
  - FAQ: 'faq.md'
  - License: 'license.md'
  - What and Why:
    - Overview: 'WhatAndWhy/overview.md'
    - Layering: 'WhatAndWhy/layers.md'
    - Componentization: 'WhatAndWhy/componentization.md'
    - Layout: 'WhatAndWhy/layout.md'
  - Where:
    - Project Resources: 'Where/project_resources.md'
    - External Resources: 'Where/external_resources.md'
  - How:
    - Release Process: 'How/release_process.md'
    - Downstream Integration: 'How/downstream_integration.md'
    - Contributing: 'How/contributing.md'
    - Upstream Integration: 'How/upstream_integration.md'
  - Usage Docs:
    - Docs: "UsageDocs/usagedocs.md"
  - Developer Docs:
    - Docs: "DeveloperDocs/developerdocs.md"

